/*******************************************************************************
 * @file mech_launcher.cpp
 * @brief Implementation of launcher mechanism controller (stepper + flywheels)
 *
 * The DRV8825 stepper driver accepts:
 *   STEP   – rising-edge triggered, one step per pulse
 *   DIR    – HIGH/LOW sets rotation direction (latched on STEP rising edge)
 *   nSLEEP – active-low sleep input; LOW = sleep, HIGH = awake
 *
 * STEP pulses are generated by a PIO state machine running the
 * stepper_pulse.pio program.  The SM accepts a pulse count via its TX FIFO,
 * emits exactly that many rising edges on the sideset pin, then pushes a
 * completion token into its RX FIFO.  This gives cycle-accurate pulse
 * counts with zero CPU overhead during a burst.
 *
 * The state machine in update() kicks one increment (40 pulses = 1/5 rev)
 * every LAUNCHER_INCREMENT_INTERVAL_MS while the launcher is enabled.
 * Flywheels remain running between increments.
 *
 * Sleep management:
 *   - On disable: abort any in-progress PIO burst, force STEP LOW, assert
 *     nSLEEP LOW, stop flywheels.
 *   - On enable:  start flywheels, wait spin-up (non-blocking), de-assert
 *     nSLEEP HIGH, wait wake delay (non-blocking), then begin increments.
 ******************************************************************************/

/* Includes ------------------------------------------------------------------*/
#include "mech_launcher.h"
#include "config.h"
#include "pinout.h"
#include "error_handler.h"
#include "pico/stdlib.h"
#include "hardware/clocks.h"
#include "hardware/pio.h"

/* Generated PIO header (created by pico_generate_pio_header in CMakeLists) */
#include "stepper_pulse.pio.h"


/* Method Definitions --------------------------------------------------------*/

MechLauncher::MechLauncher()
  : m_initialized(false)
  , m_running(false)
  , m_flywheelsRunning(false)
  , m_stepperRunning(false)
  , m_state(STATE_IDLE)
  , m_spinupStartMs(0)
  , m_wakeStartMs(0)
  , m_lastIncrementMs(0)
  , m_incrementActive(false)
  , m_pioSmIdx(0)
  , m_pioOffset(0)
  , m_pioInstance(nullptr)
  , m_flywheelDriver()
{
}

MechLauncher::~MechLauncher()
{
  if (m_initialized)
  {
    setEnabled(false);
  }
}

bool MechLauncher::init(void)
{
  /* ---- nSLEEP pin (digital output) ------------------------------------- */
  gpio_init(PIN_LAUNCHER_NSLEEP);
  gpio_set_dir(PIN_LAUNCHER_NSLEEP, GPIO_OUT);
  gpio_put(PIN_LAUNCHER_NSLEEP, 0);              /* Start in sleep          */

  /* ---- DIR pin (digital output) ---------------------------------------- */
  gpio_init(PIN_LAUNCHER_DIR);
  gpio_set_dir(PIN_LAUNCHER_DIR, GPIO_OUT);
  gpio_put(PIN_LAUNCHER_DIR, LAUNCHER_DIR_FORWARD);

  /* ---- PIO setup for STEP pin ------------------------------------------ */
  PIO pio = pio0;

  /* Claim a state machine */
  int sm = pio_claim_unused_sm(pio, false);
  if (sm < 0)
  {
    /* pio0 full — try pio1 */
    pio = pio1;
    sm  = pio_claim_unused_sm(pio, false);
    if (sm < 0)
    {
      DEBUG_PRINTF("[Launcher] No free PIO state machine\n");
      ERROR_REPORT(ERROR_HW_INIT_FAILED);
      return false;
    }
  }
  m_pioInstance = pio;
  m_pioSmIdx    = (uint)sm;

  /* Load the PIO program into instruction memory */
  if (!pio_can_add_program(pio, &stepper_pulse_program))
  {
    DEBUG_PRINTF("[Launcher] PIO instruction memory full\n");
    pio_sm_unclaim(pio, m_pioSmIdx);
    ERROR_REPORT(ERROR_HW_INIT_FAILED);
    return false;
  }
  m_pioOffset = pio_add_program(pio, &stepper_pulse_program);

  /*
   * Configure the state machine:
   *   - Sideset pin = PIN_LAUNCHER_STEP (directly drives STEP)
   *   - Clock divider sized so each PIO cycle = 1 / (step_rate * 2)
   *     because one pulse = 2 cycles (HIGH + LOW)
   */
  pio_sm_config cfg = stepper_pulse_program_get_default_config(m_pioOffset);

  /* Map sideset to the STEP pin */
  sm_config_set_sideset_pins(&cfg, PIN_LAUNCHER_STEP);

  /* Clock divider: each PIO instruction = half a STEP period */
  float sysClkHz = (float)clock_get_hz(clk_sys);
  float divider  = sysClkHz / ((float)LAUNCHER_STEP_RATE_HZ * 2.0f);
  sm_config_set_clkdiv(&cfg, divider);

  /* Initialise STEP pin as a PIO output (driven by sideset) */
  pio_gpio_init(pio, PIN_LAUNCHER_STEP);
  pio_sm_set_consecutive_pindirs(pio, m_pioSmIdx, PIN_LAUNCHER_STEP, 1, true);

  /* Apply configuration and enable the SM.
   * The SM will immediately block on `pull block` with STEP LOW. */
  pio_sm_init(pio, m_pioSmIdx, m_pioOffset, &cfg);
  pio_sm_set_enabled(pio, m_pioSmIdx, true);

  /* ---- Flywheel motors ------------------------------------------------- */
  bool flywheelOk = true;

  flywheelOk &= m_flywheelDriver.configureMotor(
    MotorDriver::MOTOR_A,
    PIN_LAUNCHER_LEFT_ENABLE,
    PIN_LAUNCHER_LEFT_DIR_FWD,
    PIN_LAUNCHER_LEFT_DIR_REV,
    PIN_INVALID);

  flywheelOk &= m_flywheelDriver.configureMotor(
    MotorDriver::MOTOR_B,
    PIN_LAUNCHER_RIGHT_ENABLE,
    PIN_LAUNCHER_RIGHT_DIR_FWD,
    PIN_LAUNCHER_RIGHT_DIR_REV,
    PIN_INVALID);

  if (!flywheelOk)
  {
    DEBUG_PRINTF("[Launcher] Flywheel motor configuration FAILED\n");
    return false;
  }

  m_flywheelDriver.stopAll(MotorDriver::STOP_COAST);

  m_initialized = true;

  DEBUG_PRINTF("[Launcher] PIO stepper initialized  sm=%lu  offset=%lu  "
               "step_rate=%d Hz  steps/incr=%d  interval=%d ms  dir=%d  "
               "nSLEEP=GPIO%d (sleeping)\n",
               m_pioSmIdx, m_pioOffset,
               LAUNCHER_STEP_RATE_HZ, LAUNCHER_STEPS_PER_INCREMENT,
               LAUNCHER_INCREMENT_INTERVAL_MS, LAUNCHER_DIR_FORWARD,
               PIN_LAUNCHER_NSLEEP);
  DEBUG_PRINTF("[Launcher] Flywheels initialized  speed=%d permil  "
               "spinup_delay=%d ms\n",
               LAUNCHER_FLYWHEEL_SPEED_PERMIL, LAUNCHER_FLYWHEEL_SPINUP_MS);

  return true;
}

void MechLauncher::update(void)
{
  if (!m_initialized)
  {
    return;
  }

  switch (m_state)
  {
    case STATE_IDLE:
    {
      // Do nothing
      break;
    }

    case STATE_SPINNING_UP:
    {
      uint32_t now = to_ms_since_boot(get_absolute_time());
      if ((now - m_spinupStartMs) >= LAUNCHER_FLYWHEEL_SPINUP_MS)
      {
        wakeStepper();
        m_wakeStartMs = now;
        m_state       = STATE_WAKING;

        DEBUG_PRINTF("[Launcher] Spin-up complete — waking DRV8825 (%d ms)...\n",
                     LAUNCHER_WAKE_DELAY_MS);
      }
      break;
    }

    case STATE_WAKING:
    {
      uint32_t now = to_ms_since_boot(get_absolute_time());
      if ((now - m_wakeStartMs) >= LAUNCHER_WAKE_DELAY_MS)
      {
        /* DRV8825 ready — kick the first increment immediately */
        kickIncrement();
        m_lastIncrementMs = now;
        m_state           = STATE_RUNNING;

        DEBUG_PRINTF("[Launcher] DRV8825 awake — first increment kicked\n");
      }
      break;
    }

    case STATE_RUNNING:
    {
      uint32_t now = to_ms_since_boot(get_absolute_time());

      /* Check if a PIO burst is still in progress */
      if (m_incrementActive)
      {
        if (isIncrementComplete())
        {
          m_incrementActive = false;
        }
        /* else: burst still running, nothing to do */
      }
      /* If no burst is active, check if the interval has elapsed */
      else
      {
        if ((now - m_lastIncrementMs) >= LAUNCHER_INCREMENT_INTERVAL_MS)
        {
          kickIncrement();
          m_lastIncrementMs = now;
        }
      }
      break;
    }
  }
}

void MechLauncher::setEnabled(bool enable)
{
  if (!m_initialized)
  {
    return;
  }

  if (enable && (m_state == STATE_IDLE))
  {
    startFlywheels();
    m_spinupStartMs = to_ms_since_boot(get_absolute_time());
    m_state         = STATE_SPINNING_UP;
    m_running       = true;

    DEBUG_PRINTF("[Launcher] ENABLED — flywheels ON, spinning up (%d ms)...\n",
                 LAUNCHER_FLYWHEEL_SPINUP_MS);
  }
  else if (!enable && (m_state != STATE_IDLE))
  {
    stopStepper();
    stopFlywheels();

    m_state           = STATE_IDLE;
    m_running         = false;
    m_incrementActive = false;

    DEBUG_PRINTF("[Launcher] DISABLED — stepper STOPPED, flywheels OFF\n");
  }
}


/* Private methods --------------------------------------------------------- */

void MechLauncher::startFlywheels(void)
{
  m_flywheelDriver.setMotor(MotorDriver::MOTOR_A, LAUNCHER_FLYWHEEL_SPEED_PERMIL);
  m_flywheelDriver.setMotor(MotorDriver::MOTOR_B, LAUNCHER_FLYWHEEL_SPEED_PERMIL);
  m_flywheelsRunning = true;
}

void MechLauncher::stopFlywheels(void)
{
  m_flywheelDriver.stopAll(MotorDriver::STOP_COAST);
  m_flywheelsRunning = false;
}

void MechLauncher::wakeStepper(void)
{
  gpio_put(PIN_LAUNCHER_NSLEEP, 1);
}

void MechLauncher::sleepStepper(void)
{
  gpio_put(PIN_LAUNCHER_NSLEEP, 0);
}

void MechLauncher::kickIncrement(void)
{
  PIO pio = static_cast<PIO>(m_pioInstance);

  /* Drain any stale completion tokens from the RX FIFO */
  while (!pio_sm_is_rx_fifo_empty(pio, m_pioSmIdx))
  {
    (void)pio_sm_get(pio, m_pioSmIdx);
  }

  /* Push the pulse count — the PIO SM will begin immediately */
  pio_sm_put_blocking(pio, m_pioSmIdx, LAUNCHER_STEPS_PER_INCREMENT);
  m_incrementActive = true;
  m_stepperRunning  = true;
}

bool MechLauncher::isIncrementComplete(void)
{
  PIO pio = static_cast<PIO>(m_pioInstance);

  if (!pio_sm_is_rx_fifo_empty(pio, m_pioSmIdx))
  {
    /* Completion token present — consume it */
    (void)pio_sm_get(pio, m_pioSmIdx);
    return true;
  }
  return false;
}

void MechLauncher::stopStepper(void)
{
  PIO pio = static_cast<PIO>(m_pioInstance);

  /*
   * To abort a burst in progress:
   *   1. Disable the SM so it stops clocking.
   *   2. Clear the FIFOs and restart the SM at the program origin
   *      (which is `pull block` → idles with STEP LOW via sideset).
   *   3. Re-enable so it blocks on the next pull.
   */
  pio_sm_set_enabled(pio, m_pioSmIdx, false);
  pio_sm_clear_fifos(pio, m_pioSmIdx);
  pio_sm_restart(pio, m_pioSmIdx);
  pio_sm_exec(pio, m_pioSmIdx,
              pio_encode_jmp(m_pioOffset));     /* Jump to program start   */
  pio_sm_set_enabled(pio, m_pioSmIdx, true);

  /* Force STEP pin LOW (sideset should already hold it, but be safe) */
  pio_sm_set_pins(pio, m_pioSmIdx, 0);

  /* Put the driver to sleep */
  sleepStepper();

  m_stepperRunning  = false;
  m_incrementActive = false;
}


/* EOF -----------------------------------------------------------------------*/
